#!/usr/bin/env bash
# CyberLab cloud bootstrap - generated by build/build-bootstrap.py; edit lab/ and scripts/, then rebuild.
# Usage: paste as EC2 / Lightsail user-data, or run: sudo bash bootstrap-cloud.sh [lab-user]
# Adds swap, an SSH-only firewall (ufw), fail2ban and automatic security updates.
# Safe to run more than once. Progress: /var/log/cyberlab-bootstrap.log
set -euo pipefail
[ "$(id -u)" -eq 0 ] || { echo "Run with sudo."; exit 1; }
exec > >(tee -a /var/log/cyberlab-bootstrap.log) 2>&1
echo "[cyberlab] bootstrap started $(date -u +%FT%TZ)"
export DEBIAN_FRONTEND=noninteractive HOME="${HOME:-/root}"

# Lab user: argument, then the sudo caller, then the usual cloud default users
LAB_USER="${1:-${SUDO_USER:-}}"
if [ -z "$LAB_USER" ] || [ "$LAB_USER" = root ]; then
  LAB_USER=""
  for u in ubuntu labadmin kali admin debian; do id "$u" >/dev/null 2>&1 && { LAB_USER="$u"; break; }; done
fi
echo "[cyberlab] lab user: ${LAB_USER:-none}"
TMP=$(mktemp -d)

# --- files ---------------------------------------------------------------
install -d -m 0755 "$(dirname $TMP/install-docker.sh)"
cat > $TMP/install-docker.sh <<'__CYBERLAB_EOF__'
#!/usr/bin/env bash
# Install Docker Engine + Compose plugin on Kali, Debian or Ubuntu.
# Usage: sudo bash install-docker.sh [username-to-add-to-docker-group]
set -euo pipefail

[ "$(id -u)" -eq 0 ] || { echo "Run with sudo."; exit 1; }
LAB_USER="${1:-${SUDO_USER:-}}"

if command -v docker >/dev/null && docker compose version >/dev/null 2>&1; then
  echo "[docker] already installed: $(docker --version)"
else
  . /etc/os-release
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg >/dev/null
  install -m 0755 -d /etc/apt/keyrings

  case "$ID" in
    kali)   DIST=debian; CODENAME=bookworm ;;   # Kali tracks Debian testing; use Docker's Debian stable repo
    debian) DIST=debian; CODENAME="$VERSION_CODENAME" ;;
    ubuntu) DIST=ubuntu; CODENAME="${UBUNTU_CODENAME:-$VERSION_CODENAME}" ;;
    *) echo "Unsupported OS: $ID (use Kali, Debian or Ubuntu)"; exit 1 ;;
  esac

  curl -fsSL "https://download.docker.com/linux/$DIST/gpg" -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/$DIST $CODENAME stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
fi

systemctl enable --now docker >/dev/null 2>&1 || true

if [ -n "$LAB_USER" ] && id "$LAB_USER" >/dev/null 2>&1; then
  usermod -aG docker "$LAB_USER"
  echo "[docker] added $LAB_USER to the docker group (log out and back in to use docker without sudo)"
fi
docker --version && docker compose version
__CYBERLAB_EOF__
chmod 0755 $TMP/install-docker.sh
install -d -m 0755 "$(dirname /opt/cyberlab/docker-compose.yml)"
cat > /opt/cyberlab/docker-compose.yml <<'__CYBERLAB_EOF__'
# CyberLab: segmented Internet / DMZ / LAN range on a single Docker host
# with Suricata IDS, Portainer GUI and an optional browser SOCKS proxy.
# Host: Kali or Ubuntu (Linux host networking is required for Suricata).
#
# Topology
#   internet 10.10.0.0/24 (br-inet)  attacker(.10) --- router(.254)
#   dmz      10.20.0.0/24 (br-dmz)   router(.254) --- juiceshop(.11), dvwa(.12)
#   lan      10.30.0.0/24 (br-lan)   dvwa(.12, dual-homed pivot) --- metasploitable(.20)
# Nothing is published on a public interface: only 127.0.0.1:9443 and 127.0.0.1:1080.

networks:
  internet:
    driver_opts:
      com.docker.network.bridge.name: br-inet
    ipam:
      config:
        - subnet: 10.10.0.0/24
  dmz:
    internal: true
    driver_opts:
      com.docker.network.bridge.name: br-dmz
    ipam:
      config:
        - subnet: 10.20.0.0/24
  lan:
    internal: true
    driver_opts:
      com.docker.network.bridge.name: br-lan
    ipam:
      config:
        - subnet: 10.30.0.0/24
  mgmt: {}   # Portainer only; no lab host is attached

volumes:
  suricata-logs:
  suricata-rules:
  portainer-data:

services:
  router:
    image: alpine:3.20
    container_name: router
    restart: unless-stopped
    cap_add: [NET_ADMIN]
    sysctls:
      - net.ipv4.ip_forward=1
    mem_limit: 64m
    networks:
      internet: { ipv4_address: 10.10.0.254 }
      dmz:      { ipv4_address: 10.20.0.254 }
    command:
      - sh
      - -c
      - |
        command -v iptables >/dev/null || apk add --no-cache iptables >/dev/null
        iptables -F FORWARD; iptables -t nat -F POSTROUTING
        iptables -P FORWARD DROP
        iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
        # Firewall policy: Internet -> DMZ web services only
        iptables -A FORWARD -s 10.10.0.0/24 -d 10.20.0.0/24 -p tcp -m multiport --dports 80,3000 -j ACCEPT
        iptables -A FORWARD -s 10.10.0.0/24 -d 10.20.0.0/24 -p icmp -j ACCEPT
        # DMZ hosts reply to the router, so they need no route changes
        iptables -t nat -A POSTROUTING -d 10.20.0.0/24 -j MASQUERADE
        echo "router ready"; exec tail -f /dev/null

  attacker:
    image: kalilinux/kali-rolling
    container_name: attacker
    hostname: attacker
    restart: unless-stopped
    cap_add: [NET_ADMIN, NET_RAW]
    mem_limit: 1536m
    tty: true
    networks:
      internet: { ipv4_address: 10.10.0.10 }
    ports:
      - "127.0.0.1:1080:1080"   # served by the socks container, which shares this network stack
    command:
      - bash
      - -c
      - |
        if ! command -v nmap >/dev/null; then
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
            nmap curl iproute2 iputils-ping netcat-openbsd sqlmap hydra nuclei ca-certificates >/dev/null
        fi
        # Nuclei vulnerability templates: fetch once (best effort; needs internet on first start)
        if command -v nuclei >/dev/null && [ ! -d "$HOME/nuclei-templates" ]; then
          nuclei -update-templates >/dev/null 2>&1 || true
        fi
        ip route replace 10.20.0.0/24 via 10.10.0.254
        echo "attacker ready"; exec tail -f /dev/null

  # Optional: lets a browser on the host reach the DMZ as the attacker (SOCKS5, no auth, host only)
  socks:
    image: serjs/go-socks5-proxy:latest
    container_name: socks
    restart: unless-stopped
    network_mode: "service:attacker"
    depends_on: [attacker]
    mem_limit: 64m
    environment:
      - REQUIRE_AUTH=false

  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: juiceshop
    restart: unless-stopped
    mem_limit: 512m
    networks:
      dmz: { ipv4_address: 10.20.0.11 }

  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    restart: unless-stopped
    mem_limit: 256m
    networks:
      dmz: { ipv4_address: 10.20.0.12 }
      lan: { ipv4_address: 10.30.0.12 }

  metasploitable:
    image: tleemcjr/metasploitable2:latest
    container_name: metasploitable
    hostname: metasploitable
    restart: unless-stopped
    mem_limit: 512m
    tty: true
    command: sh -c "/bin/services.sh && tail -f /dev/null"
    networks:
      lan: { ipv4_address: 10.30.0.20 }

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host          # needed to sniff the lab bridges
    cap_add: [NET_ADMIN, NET_RAW, SYS_NICE]
    mem_limit: 1g
    restart: unless-stopped
    depends_on: [router, dvwa, metasploitable]
    volumes:
      - suricata-logs:/var/log/suricata
      - suricata-rules:/var/lib/suricata
    # HOME_NET = protected segments, so the attacker (10.10.0.0/24) is EXTERNAL_NET
    command: >
      -i br-inet -i br-lan
      --set vars.address-groups.HOME_NET=[10.20.0.0/24,10.30.0.0/24]

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    mem_limit: 256m
    restart: unless-stopped
    networks: [mgmt]
    ports:
      - "127.0.0.1:9443:9443"   # host only; never expose to the lab or the internet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
__CYBERLAB_EOF__
chmod 0644 /opt/cyberlab/docker-compose.yml
install -d -m 0755 "$(dirname /usr/local/bin/cyberlab)"
cat > /usr/local/bin/cyberlab <<'__CYBERLAB_EOF__'
#!/usr/bin/env bash
# cyberlab - manage the segmented Docker lab
# Usage: cyberlab {up|verify|status|alerts|rules|scan <target>|reset [--full]|down|destroy}
set -uo pipefail

LAB_DIR="${LAB_DIR:-/opt/cyberlab}"
DC="docker compose --project-directory $LAB_DIR -f $LAB_DIR/docker-compose.yml"
# Optional local overrides (for example a pre-baked attacker image on offline Proxmox pods)
[ -f "$LAB_DIR/docker-compose.override.yml" ] && DC="$DC -f $LAB_DIR/docker-compose.override.yml"

wait_for_log() {   # container, text, timeout-seconds
  local c="$1" text="$2" t="${3:-600}" i=0
  printf "[wait] %s " "$c"
  until docker logs "$c" 2>&1 | grep -q "$text"; do
    sleep 5; i=$((i+5)); printf "."
    [ "$i" -ge "$t" ] && { echo " timeout"; return 1; }
  done
  echo " ok"
}

update_rules() {
  echo "[rules] downloading Emerging Threats Open rules into Suricata"
  docker exec suricata suricata-update -q && docker restart suricata >/dev/null && echo "[rules] loaded"
}

cmd_up() {
  $DC pull -q --ignore-pull-failures || echo "[up] some images could not be pulled; using local copies"
  $DC up -d
  wait_for_log router "router ready" 120
  wait_for_log attacker "attacker ready" 900   # first start installs tools (several minutes)
  if ! docker exec suricata test -s /var/lib/suricata/rules/suricata.rules 2>/dev/null; then
    update_rules
  fi
  cmd_status
  cat <<'EOF'

Lab is up.
  Attack shell : docker exec -it attacker bash
  Vuln scan    : cyberlab scan http://10.20.0.12
  IDS alerts   : cyberlab alerts
  Portainer    : https://localhost:9443   (create the admin user within 5 minutes)
  Browser      : SOCKS5 127.0.0.1:1080, then open http://10.20.0.11:3000 or http://10.20.0.12
  Self-test    : cyberlab verify
EOF
}

cmd_status() { $DC ps --format "table {{.Name}}\t{{.Status}}"; }

cmd_alerts() { docker exec -it suricata tail -n 30 -f /var/log/suricata/fast.log; }

check() {   # description, expected(pass|block), command...
  local desc="$1" expect="$2"; shift 2
  if "$@" >/dev/null 2>&1; then got=pass; else got=block; fi
  if [ "$got" = "$expect" ]; then echo "  PASS  $desc"; else echo "  FAIL  $desc (expected $expect, got $got)"; FAILS=$((FAILS+1)); fi
}

cmd_verify() {
  FAILS=0
  echo "Segmentation and service checks:"
  check "Internet -> Juice Shop 10.20.0.11:3000 allowed" pass docker exec attacker curl -s -m 5 -o /dev/null http://10.20.0.11:3000
  check "Internet -> DVWA 10.20.0.12:80 allowed"         pass docker exec attacker curl -s -m 5 -o /dev/null http://10.20.0.12
  check "Internet -> DVWA MySQL 3306 blocked"            block docker exec attacker nc -z -w 3 10.20.0.12 3306
  check "Internet -> LAN 10.30.0.20 blocked"             block docker exec attacker ping -c 1 -W 2 10.30.0.20
  check "DMZ pivot (DVWA) -> Metasploitable FTP allowed" pass docker exec dvwa bash -c 'timeout 3 bash -c "</dev/tcp/10.30.0.20/21"'
  check "DMZ and LAN have no internet access"            block docker exec dvwa bash -c 'timeout 3 bash -c "</dev/tcp/1.1.1.1/443"'
  check "Suricata rules loaded"                          pass docker exec suricata test -s /var/lib/suricata/rules/suricata.rules
  check "Portainer bound to localhost only"              block bash -c "ss -ltn | grep ':9443' | grep -v 127.0.0.1"
  check "Nuclei installed in the attacker container"     pass  docker exec attacker sh -c "command -v nuclei"

  echo "IDS detection check (sends a request with a sqlmap user agent):"
  docker exec attacker curl -s -m 5 -o /dev/null -A "sqlmap/1.8" "http://10.20.0.12/?id=1" || true
  sleep 8
  if docker exec suricata grep -qi sqlmap /var/log/suricata/fast.log 2>/dev/null; then
    echo "  PASS  Suricata raised a sqlmap alert"
  else
    echo "  WARN  no sqlmap alert yet; run 'cyberlab rules' and try again"
  fi
  [ "$FAILS" -eq 0 ] && echo "All checks passed." || { echo "$FAILS check(s) failed."; return 1; }
}

cmd_reset() {
  if [ "${1:-}" = "--full" ]; then
    echo "[reset] full: removing containers AND volumes (rules, logs, Portainer settings)"
    $DC down -v
  else
    echo "[reset] containers rebuilt from clean images; rules, logs and Portainer kept"
    $DC down
  fi
  cmd_up
}

cmd_scan() {
  local target="${1:-}"
  if [ -z "$target" ]; then
    echo "usage: cyberlab scan <target>     e.g. cyberlab scan http://10.20.0.12"
    echo "       LAN targets (10.30.0.x) need the attacker LAN-attached first."
    return 1
  fi
  echo "[scan] ensuring nuclei is present in the attacker container..."
  docker exec attacker bash -c 'command -v nuclei >/dev/null 2>&1 || { apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nuclei >/dev/null; }' \
    || { echo "[scan] could not install nuclei in the attacker container"; return 1; }
  docker exec attacker bash -c '[ -d "$HOME/nuclei-templates" ] || nuclei -update-templates >/dev/null 2>&1 || true'
  echo "[scan] running nuclei against $target"
  docker exec attacker nuclei -u "$target" -severity low,medium,high,critical -stats -no-color
}

case "${1:-}" in
  up)      cmd_up ;;
  verify)  cmd_verify ;;
  status)  cmd_status ;;
  alerts)  cmd_alerts ;;
  rules)   update_rules ;;
  scan)    cmd_scan "${2:-}" ;;
  reset)   cmd_reset "${2:-}" ;;
  down)    $DC stop ;;
  destroy) $DC down -v --rmi all ;;
  *) echo "Usage: cyberlab {up|verify|status|alerts|rules|scan <target>|reset [--full]|down|destroy}"; exit 1 ;;
esac
__CYBERLAB_EOF__
chmod 0755 /usr/local/bin/cyberlab

# --- cloud hardening --------------------------------------------------------
# Swap: add 4 GB if the host has little RAM, so 4 GB instances don't OOM.
# (t3.large has 8 GB, so this is usually skipped, but it keeps smaller plans safe.)
if ! swapon --show 2>/dev/null | grep -q . && [ ! -f /swapfile ]; then
  MEM_MB=$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo)
  if [ "${MEM_MB:-9999}" -lt 6000 ]; then
    echo "[cyberlab] adding 4 GB swap (RAM ${MEM_MB} MB)"
    fallocate -l 4G /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=4096
    chmod 600 /swapfile; mkswap /swapfile >/dev/null; swapon /swapfile
    grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  fi
fi

# Host firewall + brute-force protection + automatic security updates.
apt-get update -qq
apt-get install -y -qq ufw fail2ban unattended-upgrades >/dev/null

# Allow SSH BEFORE enabling ufw, so we never lock ourselves out. The AWS security
# group is the primary control; ufw is defense in depth.
ufw allow OpenSSH >/dev/null 2>&1 || ufw allow 22/tcp >/dev/null
ufw --force enable >/dev/null
echo "[cyberlab] ufw enabled (SSH only)"

systemctl enable --now fail2ban >/dev/null 2>&1 || true

printf 'APT::Periodic::Update-Package-Lists "1";\nAPT::Periodic::Unattended-Upgrade "1";\n' \
  > /etc/apt/apt.conf.d/20auto-upgrades
systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true
echo "[cyberlab] fail2ban and automatic security updates enabled"

# --- install ---------------------------------------------------------------
bash "$TMP/install-docker.sh" "$LAB_USER"
echo "[cyberlab] starting the lab (first start downloads about 3 GB)"
cyberlab up
cyberlab verify || echo "[cyberlab] some checks failed; rerun 'cyberlab verify' in a few minutes"
rm -rf "$TMP"
echo "[cyberlab] bootstrap done $(date -u +%FT%TZ). Reconnect over SSH, then run: cyberlab verify"
