options { directory "/var/cache/bind"; recursion yes; allow-query { any; }; };
zone "cipher.lab" {
    type master;
    file "/etc/bind/zones/db.cipher.lab";
    // AXFR refused to everyone EXCEPT the trusted host (victim, 10.30.0.30)
    allow-transfer { 10.30.0.30; };
};
